### ISSUE TITLE
Resonator GUI Fix and facing fix required

### ISSUE THREAD

**Issue by Circl3s** [MineBartekSA/Sonos#1]
Żeby było symetrycznie, obniżyłem input o 1 piksel, więc popraw to tam magicznie. Oprócz tego trzeba zrobić facing, żeby można było obracać tegesa. Nie będę w końcu już robił nic z tym interfejsem, strzałkę zostawmy, tylko czy ją pokolorujesz w kodzie, czy ja mam to zrobić? A model jest WIP, pewnie zmienie tekstury, żeby wyglądał bardziej technologiczno-magicznie, a nie kamienno-kamiennie.

**Comment by MineBartekSA** [comment]
Więc sam blok jest już funkcjonalny, ale ta strzałka w GUI działa 2/10 ale spokojnie jakoś to naprawię (czuję że będę musiał się pobawić pacjentami bo coś mi się wydaje że client nie dostaje od servera informacji o progresie). A to z facing to (myślę) że to co zrobiłem dobrze pobiera w którą stronę ma być, ale nie obraca (jeszcze). Wszystko z prądem i przetważaniem rawSono na sonoPrima działa idealnie, tylko można zmienić totalProgressTime i Energy transfer rate.

**Comment by MineBartekSA** [comment]
Fixed
