### ISSUE TITLE
All the Sono Ore audio issues because I don't want to spam xd

### ISSUE THREAD

**Issue by Circl3s** [MineBartekSA/Sonos#2]
- [x] Audio kept playing after I destroyed the block
- [x] Audio restarted after a short while in the pause menu
- [x] Audio kept playing after the block deactivated
- [x] Clips slightly overlap
- [x] Server freezes if more than one is playing
- [x] Sometimes audio stops playing before the block is deactivated

Will add more details / bugs as I test more.

**Comment by MineBartekSA** [comment]
Gotta rewrite this! Because server is freezing =/

**Comment by MineBartekSA** [comment]
Fixed in this [commit](https://github.com/MineBartekSA/Sonos/commit/302be5cb4139a3a3b8a2b9d0d598825df9390e13)

At least most of them!!

**Comment by Circl3s** [comment]
May I suggest scrapping the redstone-like random mechanic and make a more stable random system. When the block is activated it gets a random duration/random number of audio loops it has to play.

**Comment by MineBartekSA** [comment]
Yeah, i guess I'll work on that

**Comment by MineBartekSA** [comment]
It dose not work as I'd like it to, but the code is ok and the sound just stops playing for some reason.
If you set [here](https://github.com/MineBartekSA/Sonos/blob/master/src/main/java/com/minebarteksa/sonos/tileentity/SonoOreEntity.java#L82) more than 56 then the bug will appear (for some reason), but it gives a nice 28 seconds max of sound and two full sound plays

**Comment by MineBartekSA** [comment]
I'll ask on Minecraft Forge Forum for help tho

**Comment by MineBartekSA** [comment]
As of this commit https://github.com/MineBartekSA/Sonos/commit/22b355a1c075e8015ed2615c3a91bdaa185b6da4 SonoOre should be finally fixed!
